// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_message from "./routes/api/message.ts";
import * as $api_message_stream from "./routes/api/message/stream.ts";
import * as $index from "./routes/index.tsx";
import * as $notice from "./routes/notice.tsx";
import * as $ChatContainer from "./islands/ChatContainer.tsx";
import * as $MessageList from "./islands/MessageList.tsx";
import * as $MessageSender from "./islands/MessageSender.tsx";
import * as $Username from "./islands/Username.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/message.ts": $api_message,
    "./routes/api/message/stream.ts": $api_message_stream,
    "./routes/index.tsx": $index,
    "./routes/notice.tsx": $notice,
  },
  islands: {
    "./islands/ChatContainer.tsx": $ChatContainer,
    "./islands/MessageList.tsx": $MessageList,
    "./islands/MessageSender.tsx": $MessageSender,
    "./islands/Username.tsx": $Username,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
